export enum AuditLogLevel {
  INFO = 'INFO',
  WARN = 'WARN',
  SECURITY_ALARM = 'SECURITY_ALARM',
}

export enum AuditEvent {
  AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED',
  AUTH_REGISTER = 'AUTH_REGISTER',
  AUTH_LOGOUT = 'AUTH_LOGOUT',
  AUTH_REVOKE_ALL = 'AUTH_REVOKE_ALL',
  AUTH_TOKEN_ROTATED = 'AUTH_TOKEN_ROTATED',
  AUTH_TOKEN_REUSE_DETECTED = 'AUTH_TOKEN_REUSE_DETECTED',

  USER_PROFILE_UPDATED = 'USER_PROFILE_UPDATED',
  USER_PASSWORD_CHANGED = 'USER_PASSWORD_CHANGED',

  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
  ORDER_CANCELLED_RESTOCKED = 'ORDER_CANCELLED_RESTOCKED',

  PAYMENT_ATTEMPT = 'PAYMENT_ATTEMPT',
  PAYMENT_WEBHOOK_HMAC_INVALID = 'PAYMENT_WEBHOOK_HMAC_INVALID',

  MEDIA_UPLOADED = 'MEDIA_UPLOADED',
  MEDIA_REJECTED = 'MEDIA_REJECTED',

  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  ADMIN_ACCESS_DENIED = 'ADMIN_ACCESS_DENIED',
}

export interface SecurityAuditEntry {
  timestamp: string;
  level: AuditLogLevel;
  event: AuditEvent;
  ip?: string;
  userId?: string;
  resourceId?: string;
  details?: Record<string, unknown>;
}
